### ISSUE TITLE
Possible error with JSON serialization

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/clc-java-sdk#128]
```
Now I have gotten past the class loading errors only to be hit by runtime errors: 
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request
       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
       at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
       at com.centurylink.cloud.sdk.base.services.client.DataCentersClient.findAllDataCenters(DataCentersClient.java:96)
       at com.centurylink.cloud.sdk.base.services.dsl.DataCenterService.findAll(DataCenterService.java:50)
       at com.centurylink.cloud.sdk.base.services.dsl.DataCenterService.findLazy(DataCenterService.java:46)
       at com.centurylink.cloud.sdk.server.services.dsl.TemplateService.lambda$findLazy$58(TemplateService.java:54)
       at com.centurylink.cloud.sdk.server.services.dsl.TemplateService$$Lambda$23/349420578.apply(Unknown Source)
       at com.centurylink.cloud.sdk.core.services.filter.evaluation.SingleFilterEvaluation.applyFindLazy(SingleFilterEvaluation.java:37)
       at com.centurylink.cloud.sdk.core.services.filter.AbstractResourceFilter.applyFindLazy(AbstractResourceFilter.java:40)
       at com.centurylink.cloud.sdk.server.services.dsl.TemplateService.findLazy(TemplateService.java:52)
       at com.centurylink.cloud.sdk.server.services.dsl.TemplateService.findLazy(TemplateService.java:34)
       at com.centurylink.cloud.sdk.core.services.filter.FilterService.find(FilterService.java:38)
       at com.centurylink.cloud.sdk.core.services.QueryService.findByRef(QueryService.java:45)
       at com.centurylink.cloud.sdk.server.services.dsl.domain.server.ServerConverter.buildCreateServerRequest(ServerConverter.java:53)
       at com.centurylink.cloud.sdk.server.services.dsl.ServerService.create(ServerService.java:91)
       at com.ko.na.CLC.exec(CLC.java:35)
       at com.ko.na.CLC.main(CLC.java:63)
Caused by: javax.ws.rs.ProcessingException: Unable to invoke request
       at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
       at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
       at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:195)
       at com.centurylink.cloud.sdk.core.auth.client.LoginClient.login(LoginClient.java:41)
       at com.centurylink.cloud.sdk.core.auth.services.BearerAuthentication.requestNewSessionCredentials(BearerAuthentication.java:72)
       at com.centurylink.cloud.sdk.core.auth.services.BearerAuthentication.requestSessionCredentialsIfNeeded(BearerAuthentication.java:56)
       at com.centurylink.cloud.sdk.core.auth.services.BearerAuthentication.getAccountAlias(BearerAuthentication.java:92)
       at com.centurylink.cloud.sdk.core.client.AuthenticatedSdkHttpClient.client(AuthenticatedSdkHttpClient.java:45)
       at com.centurylink.cloud.sdk.base.services.client.DataCentersClient.loadAllDataCenters(DataCentersClient.java:104)
       at com.centurylink.cloud.sdk.base.services.client.DataCentersClient.access$100(DataCentersClient.java:36)
       at com.centurylink.cloud.sdk.base.services.client.DataCentersClient$2.load(DataCentersClient.java:89)
       at com.centurylink.cloud.sdk.base.services.client.DataCentersClient$2.load(DataCentersClient.java:86)
       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
       ... 18 more
Caused by: javax.ws.rs.ProcessingException: could not find writer for content-type application/json type: com.centurylink.cloud.sdk.core.auth.client.domain.LoginRequest
       at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:40)
       at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:138)
       at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:117)
       at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100)
       at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:122)
       at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:341)
       at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:558)
       at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:524)
       at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:423)
at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:281)
```

**Comment by markramach** [comment]
`could not find writer for content-type application/json type`

Typically this means there is no serialization provider for the media type on the classpath. I would verify that a supported JSON serialization provider like Jackson is present in the dependency hierarchy.

**Comment by drcreager** [comment]
I have three Jackson jars in my path as shown below: 
![image](https://cloud.githubusercontent.com/assets/13224407/8652231/9724fbce-294b-11e5-9654-e79b2feca4d8.png)

Is there some other Jackson library that I require.

**Comment by idrabenia** [comment]
Hi @drcreager,

Yep, I think it will require also [this library](http://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-jackson2-provider). It contains adapters of Jackson JSON to REST Easy HTTP Client.

**Comment by idrabenia** [comment]
If you will require some other help, or maybe you will have some adhoc questions about installation and usage - feel free to contact me. 

My contacts is

Email: ilya.drabenia(at)altoros.com

**Comment by drcreager** [comment]
I fixed my JAVA_HOME (Ilya advised that it has to point to the JDK not the JRE) and that got me past the build errors.  Now I'm trying to get started, but the user guide is all .md files that my system doesn't recognize.  Can you advise as to what .md files are, so I can download a reader.

**Comment by push1st1k** [comment]
Hi @drcreager,

There is markdown file format. You may open .md file in any text editor, copy the content from file and paste it here http://dillinger.io/

or you may just find information [here](https://github.com/CenturyLinkCloud/clc-java-sdk/wiki)

**Comment by drcreager** [comment]
Thank you

That was very helpful.


Daniel R Creager
[C-I-T-logo-vrt-glow]
The Coca-Cola Company
voice:    +1 404-676-6129
Mobile:  +1 404-803-1794
fax:       +1 404-598-6129
dcreager@coca-cola.com<mailto:dcreager@coca-cola.com>
